# Generated by Django 4.2.19 on 2025-02-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=250)),
                ('lift_ticket', models.CharField(choices=[('Ikon Pass', 'Ikon Pass'), ('Epic Pass', 'Epic Pass'), ('Day Lift Ticket', 'Day Lift Ticket')], default='Day Lift Ticket', max_length=20)),
            ],
        ),
    ]
