# Generated by Django 4.2.19 on 2025-02-20 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresorts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('guest', models.CharField(max_length=100)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresorts_app.resort')),
            ],
        ),
    ]
