# Generated by Django 4.2.19 on 2025-02-20 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresorts_app', '0002_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('buddy', models.CharField(max_length=100)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresorts_app.resort')),
            ],
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
